export const PRODUCT_LIST_FETCH_REQUEST = "PRODUCT_LIST_FETCH_REQUEST";
export const PRODUCT_LIST_FETCH_SUCCESS = "PRODUCT_LIST_FETCH_SUCCESS";
export const PRODUCT_LIST_FETCH_FAIL = "PRODUCT_LIST_FETCH_FAIL";

export const PRODUCT_DETAILS_FETCH_SUCCESS = "PRODUCT_DETAILS_FETCH_SUCCESS"
export const PRODUCT_DETAILS_FETCH_FAIL = "PRODUCT_DETAILS_FETCH_FAIL"
export const PRODUCT_DETAILS_FETCH_REQUEST = "PRODUCT_DETAILS_FETCH_REQUEST"



export const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST"
export const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS"
export const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL"
